"""add target_group_ids to publish_posts

Revision ID: 50aa0fd31aaa
Revises: e70654156e25
Create Date: 2026-04-22 17:01:40.806366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50aa0fd31aaa'
down_revision: Union[str, Sequence[str], None] = 'e70654156e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_posts', sa.Column('target_group_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_posts', 'target_group_ids')
    # ### end Alembic commands ###
