"""add publish_posts, bot_configs, ai_insights

Revision ID: e70654156e25
Revises: 4936afaaab05
Create Date: 2026-04-22 15:23:05.070540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70654156e25'
down_revision: Union[str, Sequence[str], None] = '4936afaaab05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_id'), 'bot_configs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_configs_key'), 'bot_configs', ['key'], unique=True)
    op.create_table('publish_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_paths', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_groups', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_posts_id'), 'publish_posts', ['id'], unique=False)
    op.drop_index('ix_bot_config_id', table_name='bot_config')
    op.drop_index('ix_bot_config_key', table_name='bot_config')
    op.drop_table('bot_config')
    op.add_column('ai_insights', sa.Column('insight', sa.Text(), nullable=False))
    op.add_column('ai_insights', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('ai_insights', 'confidence')
    op.drop_column('ai_insights', 'content')
    op.drop_column('ai_insights', 'applied')
    op.drop_column('ai_insights', 'insight_type')
    op.add_column('posts', sa.Column('cycle_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cycle_number')
    op.add_column('ai_insights', sa.Column('insight_type', sa.VARCHAR(), nullable=True))
    op.add_column('ai_insights', sa.Column('applied', sa.BOOLEAN(), nullable=True))
    op.add_column('ai_insights', sa.Column('content', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('confidence', sa.FLOAT(), nullable=True))
    op.drop_column('ai_insights', 'category')
    op.drop_column('ai_insights', 'insight')
    op.create_table('bot_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_config_key', 'bot_config', ['key'], unique=1)
    op.create_index('ix_bot_config_id', 'bot_config', ['id'], unique=False)
    op.drop_index(op.f('ix_publish_posts_id'), table_name='publish_posts')
    op.drop_table('publish_posts')
    op.drop_index(op.f('ix_bot_configs_key'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    # ### end Alembic commands ###
